FROM python:3.11-slim

WORKDIR /app

# Instala dependências Python
COPY streamlit_requirements.txt .
RUN pip install --no-cache-dir -r streamlit_requirements.txt

# Copia a aplicação
COPY . .

# Expor porta padrão do Streamlit
EXPOSE 8501

# Rodar Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]